### ISSUE TITLE
Small issues with the examples in the POD synopsis

### ISSUE THREAD

**Issue by mmitch** [briandfoy/app-url#2]
I've spotted a small issue in the SYNOPSIS part of the POD:
```bash
$ url '%P' http://www.example.com/a/b/c
	/a/b/c
```

* The example is repeated twice. The fourth example should probably show a different format parameter than the third.
* `%P` is listed as the format parameter for the password (which does not exist in the example URL) – to get the output `/a/b/c` I think `%a` should be used.

**Comment by briandfoy** [comment]
Fixed in c1f5294eb15d8e5504d1a414aa44206c36473bb4. Thanks,
